
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: hello
        name: Run Hello World action
        uses: yedidyar/yedidya-action/hello-world@main
        with:
          who-to-greet: GitHub Actions
      - name: Display output
        run: echo "Greeted at ${{ steps.hello.outputs.time }}"
name: Local Test
on: [push]

